//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace o3DLib.Sketching
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Windows.Media.Media3D;
    using System.Collections.ObjectModel;
    using System.Windows;
    using Extensions;

    public class Line2D : Entity2D, ISegment
	{
        public Line2D(Sketch parent):base(parent) { }
        public Line2D(Sketch parent, Point3D start, Point3D end) : base(parent,start,end) {}
        public Line2D(Sketch parent, Point2D start, Point2D end) : base(parent, start, end) { }

        public override Point2D GetKeyPoint(KeyPointType type)
        {
            switch(type)
            {
                case KeyPointType.Start: return Points2D[0];
                case KeyPointType.End: return Points2D[1];
                case KeyPointType.Middle: return new Point2D(Points2D[0].Point.Middle(Points2D[1].Point)); //todo Musi byt Invisible + doriesit Parent atd...
                default: return null;
            }
        }

        
        public IPoint StartPoint {
            get
            {
                return this.GetKeyPoint(KeyPointType.Start);
            }
        }

        public IPoint EndPoint
        {
            get
            {
                return this.GetKeyPoint(KeyPointType.End);
            }
        }

    }
}

