//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace o3DLib.Sketching.Relations2D
{
	using o3DLib.Sketching;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Horizontal : Relation2D, IRelation2D
	{

        private IList<Relation2D> childRelations = new List<Relation2D>();

        public Horizontal(Entity2D entity)
        {
                      
        }

        public Horizontal(Point2D point1, Point2D point2)
        {

        }

		public override bool Satisfy()
		{
			throw new System.NotImplementedException();
		}

	}
}

