//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace States
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DrawingState : IState
	{
		public virtual void onClick()
		{
			throw new System.NotImplementedException();
		}

		public virtual void onMouseMove()
		{
			throw new System.NotImplementedException();
		}

	}
}

