//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace States
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>Represents a state that can provide proxy to the events described by the methods.</remarks>
	public interface IState 
	{
		void onClick();

		void onMouseMove();

	}
}

