//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using States;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MainWindow
{
	public virtual IState IState
	{
		get;
		set;
	}

	public virtual void getCurrentState()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setCurrentState(object IState state)
	{
		throw new System.NotImplementedException();
	}

}

