//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sketching
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Relations2D;

    public class Entity2D : IRelatable
	{
		public virtual IList<Point2D> Points
		{
			get;
			set;
		}

        public IEnumerable<IRelation2D> IRelation2D
        {
            get
            {
                throw new NotImplementedException();
            }

            set
            {
                throw new NotImplementedException();
            }
        }

        public IEnumerable<Relation2D> Relation2D
        {
            get
            {
                throw new NotImplementedException();
            }

            set
            {
                throw new NotImplementedException();
            }
        }

        public virtual Point2D GetKeyPoint(KeyPointType type)
		{
			throw new System.NotImplementedException();
		}

		public virtual bool SatisfyRelations()
		{
			throw new System.NotImplementedException();
		}

		public virtual IList<Point2D> GetRelatingPoints()
		{
			throw new System.NotImplementedException();
		}

	}
}

