//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sketching
{
	using Sketching.Relations2D;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IRelatable 
	{
		IList<Relation2D> Relation2D { get;set; }

		IList<Point2D> GetRelatingPoints();

	}
}

