//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sketching
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Line2D : Entity2D
	{
		public virtual void moveTo(double x, double y)
		{
			throw new System.NotImplementedException();
		}

		public virtual void rotate(double angle)
		{
			throw new System.NotImplementedException();
		}

		public virtual void stretch(double newLength)
		{
			throw new System.NotImplementedException();
		}

	}
}

