//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace o3DLib.Sketching
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Windows;

    public class Sketch: System.Windows.Media.Media3D.ModelVisual3D
	{



        public RefPlane RefPlane
        {
            get { return (RefPlane)GetValue(RefPlaneProperty); }
            set { SetValue(RefPlaneProperty, value); }
        }
        // Using a DependencyProperty as the backing store for RefPlane.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty RefPlaneProperty =
            DependencyProperty.Register("RefPlane", typeof(RefPlane), typeof(Sketch), new PropertyMetadata(null));



        public List<Entity2D> Entities
        {
            get { return (List<Entity2D>)GetValue(EntitiesProperty); }
            set { SetValue(EntitiesProperty, value); }
        }
        public static readonly DependencyProperty EntitiesProperty =
            DependencyProperty.Register("Entities", typeof(List<Entity2D>), typeof(Sketch), new PropertyMetadata(new List<Entity2D>()));



    }
}

